# Generated by Django 6.0 on 2026-01-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Audit & Assurance', 'Audit & Assurance'), ('Tax & Regulatory', 'Tax & Regulatory'), ('Business Advisory', 'Business Advisory'), ('Management', 'Management')], max_length=100)),
                ('bio', models.TextField()),
                ('specialization', models.CharField(help_text='e.g., Tax Law, International Audit', max_length=200)),
                ('qualifications', models.TextField(help_text='List of professional designations (e.g., ICAG, MBA)')),
                ('linkedin_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(upload_to='team/')),
                ('order_weight', models.PositiveIntegerField(default=10, help_text='Lower values appear first (Managing Partners = 1)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_weight', 'first_name'],
            },
        ),
    ]
