# Generated by Django 6.0 on 2026-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_management',
            field=models.BooleanField(default=False, help_text='Check this for members of the Firm Leadership team.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
