# Generated by Django 4.2 on 2023-11-20 12:00

from django.db import migrations


def populate_services(apps, schema_editor):
    Service = apps.get_model('estimation', 'Service')
    initial_services = [
        {'name': 'Design Ceiling', 'cost_per_sqm': 200},
        {'name': 'Flat Ceiling', 'cost_per_sqm': 160},
        {'name': 'Wall Cladding', 'cost_per_sqm': 170},
        {'name': 'Partition', 'cost_per_sqm': 220},
        {'name': 'Acoustic System', 'cost_per_sqm': 200},
    ]
    for service_data in initial_services:
        Service.objects.create(**service_data)


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_services),
    ]
