# Generated by Django 6.0 on 2025-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_productimage'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='Select materials from the catalogue usually required for this service.', related_name='suggested_for_services', to='catalogue.product'),
        ),
    ]
