# Generated by Django 6.0 on 2025-12-23 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='e.g. Master Bedroom POP Ceiling', max_length=200)),
                ('description', models.TextField(help_text='Describe your vision or the dimensions of the space.')),
                ('inspiration_image', models.ImageField(blank=True, null=True, upload_to='custom_requests/inspiration/')),
                ('site_photo', models.ImageField(blank=True, help_text='Photo of the current wall/ceiling.', null=True, upload_to='custom_requests/sites/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True, help_text='Notes from the Sellux team.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
