# Generated by Django 6.0 on 2025-12-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text="Notes from the Sellux team. Adding a note will mark this as 'Quote Sent'."),
        ),
    ]
