# Generated by Django 6.0 on 2025-12-24 17:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_requests', '0002_alter_customrequest_admin_note'),
        ('orders', '0003_alter_order_options_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='estimated_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated area in square feet', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_project', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='service_type',
            field=models.CharField(choices=[('pop_ceiling', 'POP Ceiling Design'), ('cornice_install', 'Cornice Installation'), ('drywall_partition', 'Drywall/Partitioning'), ('skimming', 'Skimming & Finishing'), ('custom_furniture', 'Custom Joinery/Furniture')], default='pop_ceiling', max_length=50),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='site_photo',
            field=models.ImageField(blank=True, null=True, upload_to='custom_requests/sites/'),
        ),
        migrations.AlterField(
            model_name='customrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted & Awaiting Payment'), ('paid', 'Paid & Scheduled'), ('rejected', 'Declined')], default='pending', max_length=20),
        ),
    ]
