# Generated by Django 6.0 on 2025-12-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_product'),
        ('orders', '0002_remove_order_catalogue_item_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogueItem',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.category'),
        ),
    ]
