# Generated by Django 6.0 on 2026-01-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about/')),
                ('main_content', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('professional_pedigree', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="e.g., 'bi-gem' for a diamond icon. Use Bootstrap Icons.", max_length=100)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='about.aboutpage')),
            ],
        ),
    ]
