# Generated by Django 6.0 on 2025-12-23 18:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('completion_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
