# Generated by Django 6.0 on 2025-12-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_productimage'),
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Optional: The original state (Before)', null=True, upload_to='portfolio/before/'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. East Legon, Accra', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='materials_used',
            field=models.ManyToManyField(blank=True, related_name='used_in_projects', to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('institutional', 'Institutional')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='The final result (After)', upload_to='portfolio/after/'),
        ),
    ]
