# Generated by Django 6.0 on 2026-01-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ShippingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Enter percentage, e.g., 15 for 15%', max_digits=5)),
                ('delivery_fee_per_100', models.DecimalField(decimal_places=2, help_text='Additional fee per 100 GHS worth of goods', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
    ]
