# Generated by Django 6.0 on 2025-12-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Notes for the customer regarding order status (e.g. tracking numbers, delivery time estimates).'),
        ),
    ]
