# Generated by Django 6.0 on 2025-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_admin_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, help_text='e.g. mobile_money, card', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Notes for the customer regarding order status.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
